# -*- coding: utf-8 -*-
"""Integrasi-Trapezoid.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-mR4PVF4BqopnKGxP4wt5dGt9FkhMv9Y

Gina Nabila (21120122130055)

**Metode Numerik - Kelas D**

**Metode integrasi trapezoid**
"""

import numpy as np
import time

# Fungsi dari soal yang akan diintegrasikan
def fungsi(x):
    return 4 / (1 + x**2)

# Fungsi penyelesaian dengan metode integrasi trapezoid
def integrasi_trapezoid(f, a, b, N):
    x = np.linspace(a, b, N+1)
    y = f(x)
    h = (b - a) / N
    integral = (h / 2) * (y[0] + 2 * np.sum(y[1:-1]) + y[-1])
    return integral

# Nilai referensi pi
nilai_pi = 3.14159265358979323846

# Variasi nilai N yang digunakan
nilai_N = [10, 100, 1000, 10000]

# Hasil penyelesaian
for N in nilai_N:
    waktu_mulai = time.time()
    estimasi_pi = integrasi_trapezoid(fungsi, 0, 1, N)
    waktu_selesai = time.time()

    # Menghitung galat RMS
    galat_rms = np.sqrt((estimasi_pi - nilai_pi)**2)

    # Menghitung waktu eksekusi
    waktu_eksekusi = waktu_selesai - waktu_mulai

    # Menampilkan hasil
    print(f"N = {N}")
    print(f"Estimasi nilai pi = {estimasi_pi}")
    print(f"Galat RMS = {galat_rms}")
    print(f"Waktu eksekusi = {waktu_eksekusi} detik\n")